import requests
"""
Написати 25 XPath та 25 CSS локаторів для сайту https://qauto2.forstudy.space/
"""

username = "guest"
passwd = "welcome2qauto"
url = f"https://{username}:{passwd}@qauto2.forstudy.space"

ebutton_1 = "//div[]"

# Розробила 25 XPath та 25 CSS локаторів для сайту https://www.glossier.com/

# 25 XPath локаторів для сайту glossier.com

logo = "//i[contains(@class, 'icon--logo')]"
logo_text = "//span[text()='Glossier']"
promo_text_xpath = "//span[contains(@class, 'promo-bar__text') and contains(., 'Free standard shipping')]"
you_look_good_text = "//span[contains(@class, 'header__logo-hover-text')]"
hero_wrapper = "//div[@id='mediaWrapper']"
country_selector = "//select[@name='country_code']"
search_button = "//button[contains(text(),'Search')]"
shop_makeup_button = "//div[contains(@class, 'btn') and contains (.,'Shop Makeup')]"
shop_makeup_button = "//div[contains(@class, 'btn') and contains (.,'Shop Skincare')]"
fragrance_link = "//a[@href='/collections/fragrance']"
sets_link = "//a[@href='/collections/sets']"
email_input = "//input[@aria-label='Email Address']"
subscription_text = "//span[contains(text(),'You can unsubscribe')]"
privacy_policy_link = "//a[contains(@class, 'footer__sub-nav-link') and normalize-space(text())='Privacy Policy']"
terms_of_use_link = "//a[contains(@class, 'footer__sub-nav-link') and normalize-space(text())='Terms of Use']"
copyright_text = "//li[normalize-space(text())='© 2025 Glossier. All rights reserved.']"
add_to_bag_balm_dotcome = "//button[@data-product-title='Balm Dotcom']"
add_to_bag_futuredew = "//button[@data-product-title='Futuredew']"
carousel_next_btn = "//button[@aria-label='Next']"
carousel_next_btn = "//button[@aria-label='Previous']"
shop_all_products = "//a[contains(@class, 'btn') and contains (., 'Shop all products')]"
choose_set_btn = "//button[contains(@class, 'js-product-set-btn') and contains(., 'Choose set')]"
key_ingredients_title = "//h2[normalize-space(text())='KEY INGREDIENTS']"
how_to_use_title = "//div[normalize-space(text())='HOW TO USE']"
login_form_xpath = "//form[@id='customer_login']"

# 25 CSS локаторів для сайту glossier.com
logo_css = "i.icon--logo span.screenreader"
how_to_use_block_css = "div.media-text__acc-menu.is-open"
you_look_good_text_css = "span.header__logo-hover-text"
hero_wrapper_css = "div#mediaWrapper"
country_selector_css = "select[name='country_code']"
search_button_css = "button.js-secondary-nav-item"
shop_makeup_button_css = "div.btn"
fragrance_link_css = "a[href='/collections/fragrance']"
body_link_css = "a[href='/collections/body']"
sets_link_css = "a[href='/collections/sets']"
email_input_css = "input[aria-label='Email Address']"
privacy_policy_link_css = "a.footer__sub-nav-link[href*='privacy-policy']"
terms_of_use_link_css = "a.footer__sub-nav-link[href*='terms-of-service']"
accessibility_link_css = "a.footer__sub-nav-link[href*='accessibility']"
copyright_text_css = "li.footer__sub-nav-colophon"
add_to_bag_balm_dotcome_css = "button[data-product-title='Balm Dotcom']"
add_to_bag_futuredew_css = "button[data-product-title='Futuredew']"
carousel_next_btn_css = "button[aria-label='Next']"
carousel_prev_btn_css = "button[aria-label='Previous']"
shop_all_products_css = "a.featured-products__header-cta" 
choose_set_btn_css = "button.js-product-set-btn"
key_ingredients_title_css = "h2.headline.h3"
how_to_use_title_css = "div.headline.media-text__headline"
login_form_css = "form#customer_login"