pipeline {
    agent {
        docker {
            image 'python:3.11'
        }
    }

    options {
        skipDefaultCheckout(true) // <<< Ось це важливо!
    }

    stages {
        stage('Checkout') {
            steps {
                sh '''
                    rm -rf repo
                    git clone https://github.com/svitlana-samsonkina/aqa_090125.git repo
                    cd repo
                    git checkout homework31
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    cd repo
                    python -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd repo
                    . ../venv/bin/activate
                    PYTHONPATH=. pytest tests --junitxml=../test-results/results.xml
                '''
            }
        }

        stage('Publish Results') {
            steps {
                junit 'repo/test-results/results.xml'
            }
        }
    }

    post {
        always {
            mail to: 'testertest7989@gmail.com',
                 subject: "Pipeline ${currentBuild.fullDisplayName} - ${currentBuild.currentResult}",
                 body: "Job result: ${currentBuild.currentResult}\nBuild: ${env.BUILD_URL}"
        }
    }
}