pipeline {
    agent {
        docker {
            image 'python:3.11'
        }
    }

    environment {
        VENV_DIR = "${env.WORKSPACE}/venv"
    }

    stages {
        stage('Checkout') {
            steps {
                // Замість "checkout scm"
                sh '''
                    git clone https://github.com/svitlana-samsonkina/aqa_090125.git repo
                    cd repo
                    git checkout homework31
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    cd repo
                    python -m venv ${VENV_DIR}
                    . ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd repo
                    . ${VENV_DIR}/bin/activate
                    pytest --junitxml=test-results/results.xml
                '''
            }
        }

        stage('Publish Results') {
            steps {
                junit 'repo/test-results/results.xml'
            }
        }
    }

    post {
        always {
            mail to: 'InsertYour@Mail.Here',
                 subject: "Pipeline ${currentBuild.fullDisplayName} - ${currentBuild.currentResult}",
                 body: "Job result: ${currentBuild.currentResult}\nBuild: ${env.BUILD_URL}"
        }
    }
}